version: "3.9"
services:
  app:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-hello-world
    tty: true
    volumes:
      - ./app:/go/app
